---
# tasks file for common
   - name: install all the build essentials
     apt:
      name:
       - build-essential
       - ca-certificates
       - curl
       - gettext
       - git
       - gunicorn
       - libbz2-dev
       - libcairo2
       - libcurl4-openssl-dev
       - libffi-dev
       - liblzma-dev
       - libpango-1.0-0
       - libpangocairo-1.0-0
       - libreadline-dev
       - libsqlite3-dev
       - libpcre3
       - libpcre3-dev
       - llvm
       - make
       - net-tools
       - nginx
       - openssl
       - python3-dev
       - postgresql-client
       - shared-mime-info
       - redis-server
       - wget
       - zlib1g-dev
       - virtualenv
       - pip
      state: latest
      update_cache: yes
   - name: Install package
     apt:
      name:
       - libcurl4-nss-dev
       - libssl-dev
      state: latest
      update_cache: yes
